name: alphapy

channels:
 - conda-forge

dependencies:
- python=3.6
- bokeh>=1.3
- ipython>=7.2
- keras>=2.2
- matplotlib>=3.0
- numpy>=1.17
- pandas>=1.0
- pyyaml>=5.0
- scikit-learn==0.22.1
- scipy>=1.1
- seaborn>=0.9
- tensorflow>=1.15
- pip:
  - arrow>=0.13
  - category_encoders>=2.1
  - iexfinance>=0.4.3
  - imbalanced-learn==0.5
  - pandas-datareader>=0.8
  - pyfolio==0.9.0
  - xgboost==0.90
